server_port: 4000
baseurl:    /
url: http://2012.beeradvent.com

markdown:    rdiscount
permalink:   /:title

rdiscount:
  extensions: []

auto: true
server: true
prose:
  metadata:
    "_posts/beer": |
      title:    "Title of your article"
      brewery:  ""
      ABV:  ""
      advent-day:  ""